parser: '@typescript-eslint/parser'
parserOptions:
  project: 
    - './**/client/tsconfig.json'
    - './**/client/tsconfig.node.json'
plugins:
  - '@typescript-eslint'
  - 'react'
  - 'jsx-a11y'
  - 'import'
extends:
  - 'airbnb'
  - 'airbnb/hooks'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:import/typescript'
settings:
  import/resolver:
    typescript: true
    node: true
rules: {
  'react/jsx-filename-extension': 'off',
  'react/react-in-jsx-scope': 'off',
  'import/extensions': 'off',
  "prefer-arrow-callback": "error"
  "no-restricted-syntax": [
    "error",
    "FunctionExpression",
    "FunctionDeclaration"
  ]
}
overrides:
  - files: vite.config.ts
    rules:
      import/no-extraneous-dependencies: off
