parser: '@typescript-eslint/parser'
parserOptions:
  project: './client/tsconfig.json'
plugins:
  - '@typescript-eslint'
  - 'react'
  - 'jsx-a11y'
  - 'import'
extends:
  - 'airbnb'
  - 'airbnb/hooks'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'
rules: {
  'react/jsx-filename-extension': 'off',
  'react/react-in-jsx-scope': 'off',
}
