name: Colosseum CI pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'development'
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_senatus:
    uses: ./.github/workflows/build-push-image.yml@testing-pipeline
    with:
      docker-context: ./senatus
      docker-file-path: ./senatus/Dockerfile
      docker-tags: ghcr.io/42dotmk/colosseum-senatus:latest

  build_client:
    uses: ./.github/workflows/build-push-image.yml@testing-pipeline
    with:
      docker-context: ./client
      docker-file-path: ./client/Dockerfile
      docker-tags: ghcr.io/42dotmk/colosseum-client-prod:latest
