name: Colosseum CI pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'development'
      - 'main'

jobs:
  build_senatus_image:
    if: github.event_name == 'pull_request'
    name: Build Senatus docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - run: |
          export senatus=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^senatus/')
          export client=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^client/')
          echo senatus has changes $senatus
          echo client has changes $client
      
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build Senatus image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./senatus
          file: ./senatus/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-senatus:latest

  build_client_image:
    if: github.event_name == 'pull_request'
    name: Build Client docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build Client production image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./client
          file: ./client/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-client-prod:latest

  push_senatus_image:
    name: Push Senatus docker image
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to ghcr.io  
        uses: docker/login-action@v3  
        with:  
          registry: ghcr.io  
          username: ${{ github.actor }}  
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Push Senatus image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
        with:
          context: ./senatus
          push: true
          file: ./senatus/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-senatus:latest

  push_client_image:
    name: Push Client docker image
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to ghcr.io  
        uses: docker/login-action@v3  
        with:  
          registry: ghcr.io  
          username: ${{ github.actor }}  
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Push Client production image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
        with:
          context: ./client
          push: true
          file: ./client/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-client-prod:latest
