name: Colosseum CI pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'development'
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  find_modified_files:
    name: Find modified files
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.changes.outputs.client }}
      senatus: ${{ steps.changes.outputs.senatus }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find modified files
        id: changes
        uses: dorny/paths-filter@v3.0.1
        with:
          filters: |
            client:
              - 'client/**'
            senatus:
              - 'senatus/**'    
        
  
  build_senatus:
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.senatus == 'true'
    with:
      docker-context: ./senatus
      docker-file-path: ./senatus/Dockerfile
      docker-tags: ghcr.io/42dotmk/colosseum-senatus:latest

  build_client:
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.client == 'true'
    with:
      docker-context: ./client
      docker-file-path: ./client/Dockerfile
      docker-tags: ghcr.io/42dotmk/colosseum-client-prod:latest
