name: Colosseum CI pipeline

on:
  push:

jobs:
  build_senatus_image:
    # if: (github.head_ref != 'development' && github.head_ref != 'main') && contains(github.event.pull_request.files, 'senatus/')
    name: Build Senatus docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - run: echo ${{ github.event.pull_request.files }}
      - name: Build Senatus image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./senatus
          file: ./senatus/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-senatus:latest

  build_client_image:
    if: (github.head_ref != 'development' && github.head_ref != 'main') && contains(github.event.pull_request.files, 'client/')
    name: Build Client docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build Client production image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./client
          file: ./client/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-client-prod:latest

  push_senatus_image:
    name: Push Senatus docker image
    if: (github.head_ref == 'development' || github.head_ref == 'main') && contains(github.event.pull_request.files, 'senatus/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to ghcr.io  
        uses: docker/login-action@v3  
        with:  
          registry: ghcr.io  
          username: ${{ github.actor }}  
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Push Senatus image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
        with:
          context: ./senatus
          push: true
          file: ./senatus/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-senatus:latest

  push_client_image:
    name: Push Client docker image
    if: (github.head_ref == 'development' || github.head_ref == 'main') && contains(github.event.pull_request.files, 'client/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to ghcr.io  
        uses: docker/login-action@v3  
        with:  
          registry: ghcr.io  
          username: ${{ github.actor }}  
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Push Client production image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
        with:
          context: ./client
          push: true
          file: ./client/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-client-prod:latest
