name: Colosseum CI pipeline

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'senatus/**'
      - 'executioner/**'
      - 'web/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  find_modified_files:
    name: Find modified files
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.changes.outputs.web }}
      senatus: ${{ steps.changes.outputs.senatus }}
      executioner: ${{ steps.changes.outputs.executioner }}
      gcc_executioner: ${{ steps.changes.outputs.gcc_executioner }}
      node_executioner: ${{ steps.changes.outputs.node_executioner }}
      python_executioner: ${{ steps.changes.outputs.python_executioner }}
      java_executioner: ${{ steps.changes.outputs.java_executioner }}
      csharp_executioner: ${{ steps.changes.outputs.csharp_executioner }}
      rust_executioner: ${{ steps.changes.outputs.rust_executioner }}
      golang_executioner: ${{ steps.changes.outputs.golang_executioner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find modified files
        id: changes
        uses: dorny/paths-filter@v3.0.1
        with:
          filters: |
            web:
              - 'web/**'
            senatus:
              - 'senatus/**'
            executioner:
              - 'executioner/**'
            gcc_executioner:
              - 'executioner/**/gcc/**'
            node_executioner:
              - 'executioner/**/nodejs/**'
            python_executioner:
              - 'executioner/**/python/**'
            java_executioner:
              - 'executioner/**/java/**'
            csharp_executioner:
              - 'executioner/**/csharp/**'
            rust_executioner:
              - 'executioner/**/rust/**'
            golang_executioner:
              - 'executioner/**/golang/**'
      
  senatus:
    name: Senatus
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.senatus == 'true'
    with:
      docker-context: ./
      docker-file-path: ./senatus/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-senatus
      docker-tags: ghcr.io/42dotmk/colosseum-senatus:latest

  web:
    name: Web (Production)
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.web == 'true'
    with:
      docker-context: ./web
      docker-file-path: ./web/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-web
      docker-tags: ghcr.io/42dotmk/colosseum-web:latest
      docker-build-args: VITE_SENATUS_URL=https://senatus.colosseum.dev

  web_dev:
    name: Web (Development)
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.web == 'true'
    with:
      docker-context: ./web
      docker-file-path: ./web/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-web
      docker-tags: ghcr.io/42dotmk/colosseum-web:dev
      docker-build-args: VITE_SENATUS_URL=https://senatus-dev.colosseum.dev

  executioner:
    name: Executioner
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.executioner == 'true'
    with:
      docker-context: ./
      docker-file-path: ./executioner/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-executioner
      docker-tags: ghcr.io/42dotmk/colosseum-executioner:latest

  gcc_executioner:
    name: GCC executioner
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.gcc_executioner == 'true'
    with:
      docker-context: ./executioner/runtimes/languages/gcc/
      docker-file-path: ./executioner/runtimes/languages/gcc/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-executioner-gcc
      docker-tags: ghcr.io/42dotmk/colosseum-executioner-gcc:latest

  node_executioner:
    name: NodeJS executioner
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.node_executioner == 'true'
    with:
      docker-context: ./executioner/runtimes/languages/nodejs/
      docker-file-path: ./executioner/runtimes/languages/nodejs/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-executioner-nodejs
      docker-tags: ghcr.io/42dotmk/colosseum-executioner-nodejs:latest

  python_executioner:
    name: Python executioner
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.python_executioner == 'true'
    with:
      docker-context: ./executioner/runtimes/languages/python/
      docker-file-path: ./executioner/runtimes/languages/python/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-executioner-python
      docker-tags: ghcr.io/42dotmk/colosseum-executioner-python:latest

  java_executioner:
    name: Java executioner
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.java_executioner == 'true'
    with:
      docker-context: ./executioner/runtimes/languages/java/
      docker-file-path: ./executioner/runtimes/languages/java/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-executioner-java
      docker-tags: ghcr.io/42dotmk/colosseum-executioner-java:latest

  csharp_executioner:
    name: C# executioner
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.csharp_executioner == 'true'
    with:
      docker-context: ./executioner/runtimes/languages/csharp/
      docker-file-path: ./executioner/runtimes/languages/csharp/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-executioner-csharp
      docker-tags: ghcr.io/42dotmk/colosseum-executioner-csharp:latest

  rust_executioner:
    name: Rust executioner
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.rust_executioner == 'true'
    with:
      docker-context: ./executioner/runtimes/languages/rust/
      docker-file-path: ./executioner/runtimes/languages/rust/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-executioner-rust
      docker-tags: ghcr.io/42dotmk/colosseum-executioner-rust:latest
    

  golang_executioner:
    name: Golang executioner
    needs: find_modified_files
    uses: ./.github/workflows/build-push-docker-image.yml
    if: needs.find_modified_files.outputs.golang_executioner == 'true'
    with:
      docker-context: ./executioner/runtimes/languages/golang/
      docker-file-path: ./executioner/runtimes/languages/golang/Dockerfile
      image-name: ghcr.io/42dotmk/colosseum-executioner-golang
      docker-tags: ghcr.io/42dotmk/colosseum-executioner-golang:latest
    