name: ci

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ghcr.io  
        uses: docker/login-action@v3  
        with:  
          registry: ghcr.io  
          username: ${{ github.actor }}  
          password: ${{ secrets.GITHUB_TOKEN }}  
      # --- Build
      - name: Build Senatus image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./senatus
          file: ./senatus/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-senatus:latest

      - name: Build Client production image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./client
          file: ./client/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-client-prod:latest
      # --- Push
      - name: Push Senatus image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
        with:
          context: ./senatus
          push: true
          file: ./senatus/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-senatus:latest

      - name: Push Client production image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
        with:
          context: ./client
          push: true
          file: ./client/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-client-prod:latest
      # --- Build
      - name: Build Executioner image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./
          file: ./executioner/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-executioner:latest

      # --- Push
      - name: Push Executioner image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
        with:
          context: ./
          push: true
          file: ./executioner/Dockerfile
          tags: ghcr.io/42dotmk/colosseum-executioner:latest
