name: Colosseum CI pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'development'
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  find_modified_files:
    runs-on: ubuntu-latest
    outputs:
      client-changes: ${{ steps.modified-files.outputs.client }}
      senatus-changes: ${{ steps.modified-files.outputs.senatus }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check modified files
        id: modified-files
        run: |
          directories="senatus client"
          for dir in $directories; do
            changes=$(git diff --name-only ${{ github.sha }} `git merge-base ${{ github.sha }} origin/${{ github.base_ref }}` | grep "^$dir/")
            if [ -z "$changes" ]; then
              echo "No files were modified in $dir"
              echo "$dir=false" >> "$GITHUB_OUTPUT"
            else
              echo "Changes detected in $dir"
              echo "$dir=true" >> "$GITHUB_OUTPUT"
            fi
          done
  
  build_senatus:
    needs: find_modified_files
    uses: ./.github/workflows/build-push-image.yml
    if: needs.find_modified_files.outputs.senatus-changes == 'true'
    with:
      docker-context: ./senatus
      docker-file-path: ./senatus/Dockerfile
      docker-tags: ghcr.io/42dotmk/colosseum-senatus:latest

  build_client:
    needs: find_modified_files
    uses: ./.github/workflows/build-push-image.yml
    if: needs.find_modified_files.outputs.client-changes == 'true'
    with:
      docker-context: ./client
      docker-file-path: ./client/Dockerfile
      docker-tags: ghcr.io/42dotmk/colosseum-client-prod:latest
