name: Linting and TypeScript checks

on:
  pull_request:
    branches:
      - development
      - main
        
jobs:
  code-linting:
    name: Running checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current code
        uses: actions/checkout@v4

      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check if changes are in specified directory
        id: check_changes
        run: echo "name=changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^${{ matrix.directory }}/' || true)" >> $GITHUB_OUTPUT
        
      - name: Run linting checks if files were done in ${{ matrix.directory }}
        if: steps.check_changes.outputs.changed
        working-directory: ${{ matrix.directory }}
        run: |
          npm run lint
          npm run ts-checks

    strategy:
      matrix:
        directory:
          - client
          - senatus
