name: Linting and TypeScript checks

on:
  pull_request:
    branches:
      - development
      - main
        
jobs:
  code-linting:
    name: Running checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check if changes are in specified directory
        id: check_changes
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)
          echo "changed=$(git diff --name-only $COMMIT_ID `git merge-base $COMMIT_ID origin/${{ github.base_ref }}` -- ':${{ matrix.directory }}/*' | grep '^${{ matrix.directory }}/' || true)" >> $GITHUB_OUTPUT
               
      - name: Installing ${{ matrix.directory }} dependencies
        if: steps.check_changes.outputs.changed
        working-directory: ${{ matrix.directory }}
        run: |
          npm install --package-lock-only --ignore-scripts
          npm ci

      - name: Run linting checks for ${{ matrix.directory }}
        if: steps.check_changes.outputs.changed
        working-directory: ${{ matrix.directory }}
        run: |
          npm run lint
          npm run ts-checks

    strategy:
      matrix:
        directory:
          - client
          - senatus
